# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndata',
            name='rawData',
            field=models.TextField(blank=True, editable=False, verbose_name='Raw data'),
        ),
        migrations.AddField(
            model_name='campaignteam',
            name='rawData',
            field=models.TextField(blank=True, editable=False, verbose_name='Raw data'),
        ),
    ]
