# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Campaign', '0002_auto_20170425_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndata',
            name='dateModified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='campaigndata',
            name='modifiedBy',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaigndata_modified_by', related_query_name='campaign_campaigndatas', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='campaignteam',
            name='dateModified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='campaignteam',
            name='modifiedBy',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaignteam_modified_by', related_query_name='campaign_campaignteams', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
    ]
