# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Campaign', '0003_auto_20170425_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('dateActivated', models.DateTimeField(blank=True, null=True, verbose_name='Date activated')),
                ('dateCompleted', models.DateTimeField(blank=True, null=True, verbose_name='Date completed')),
                ('dateRetired', models.DateTimeField(blank=True, null=True, verbose_name='Date retired')),
                ('dateModified', models.DateTimeField(blank=True, null=True, verbose_name='Date modified')),
                ('activated', models.BooleanField(default=False, verbose_name='Activated?')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed?')),
                ('retired', models.BooleanField(default=False, verbose_name='Retired?')),
                ('rawData', models.TextField(blank=True, editable=False, verbose_name='Raw data')),
                ('activatedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaign_activated_by', related_query_name='campaign_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Activated by')),
                ('batches', models.ManyToManyField(related_name='campaign_campaign_batches', related_query_name='campaign_campaigns', to='Campaign.CampaignData', verbose_name='Batches')),
                ('completedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaign_completed_by', related_query_name='campaign_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Completed by')),
                ('createdBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaign_created_by', related_query_name='campaign_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modifiedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaign_modified_by', related_query_name='campaign_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('retiredBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaign_retired_by', related_query_name='campaign_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Retired by')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_campaign_team', related_query_name='campaign_campaigns', to='Campaign.CampaignTeam', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
