# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0004_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='team',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaignName',
            field=models.CharField(default='-empty-', help_text='(max. 50 characters)', max_length=50, verbose_name='Campaign name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='teams',
            field=models.ManyToManyField(related_name='campaign_campaign_team', related_query_name='campaign_campaigns', to='Campaign.CampaignTeam', verbose_name='Teams'),
        ),
    ]
