# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0005_auto_20170501_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='teams',
            field=models.ManyToManyField(related_name='campaign_campaign_teams', related_query_name='campaign_campaigns', to='Campaign.CampaignTeam', verbose_name='Teams'),
        ),
    ]
