# Generated by ChriFe on 2019-05-18 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0009_auto_20190227_1421'),
    ]
