# Generated by ChriFe on 2019-05-18 00:39
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0009_auto_20190227_1421'),
    ]
