# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 14:35
from __future__ import unicode_literals

import Dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvitetoken',
            name='token',
            field=models.CharField(db_index=True, default=Dashboard.models.create_uuid4_token, help_text='Unique invite token', max_length=8, unique=True, verbose_name='Invite token'),
        ),
    ]
