# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0002_auto_20170425_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsegment',
            name='segmentID',
            field=models.CharField(default='-empty-', help_text='(max. 50 characters)', max_length=50, verbose_name='Segment ID'),
            preserve_default=False,
        ),
    ]
