# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0003_textsegment_segmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpair',
            name='sourceID',
            field=models.CharField(default='-empty-', help_text='(max. 50 characters)', max_length=50, verbose_name='Source ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textpair',
            name='targetID',
            field=models.CharField(default='-empty-', help_text='(max. 50 characters)', max_length=50, verbose_name='Target ID'),
            preserve_default=False,
        ),
    ]
