# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0004_auto_20170425_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpair',
            name='itemType',
            field=models.CharField(choices=[('SRC', 'Source text'), ('TGT', 'Target text'), ('REF', 'Reference text'), ('BAD', 'Bad reference'), ('CHK', 'Redundant check')], default='UNSET', max_length=5, verbose_name='Item type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textsegment',
            name='itemType',
            field=models.CharField(choices=[('SRC', 'Source text'), ('TGT', 'Target text'), ('REF', 'Reference text'), ('BAD', 'Bad reference'), ('CHK', 'Redundant check')], default='UNSET', max_length=5, verbose_name='Item type'),
            preserve_default=False,
        ),
    ]
