# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EvalData', '0005_auto_20170425_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='dateModified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='market',
            name='modifiedBy',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_market_modified_by', related_query_name='evaldata_markets', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='dateModified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='modifiedBy',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_metadata_modified_by', related_query_name='evaldata_metadatas', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='textpair',
            name='dateModified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='textpair',
            name='modifiedBy',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_textpair_modified_by', related_query_name='evaldata_textpairs', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='textsegment',
            name='dateModified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='textsegment',
            name='modifiedBy',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_textsegment_modified_by', related_query_name='evaldata_textsegments', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
    ]
