# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 04:44
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0030_objectid_taskagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectid',
            name='primaryID',
            field=models.CharField(
                db_index=True,
                help_text='(max. 50 characters)',
                max_length=50,
                verbose_name='Primary ID',
            ),
        ),
        migrations.AlterField(
            model_name='objectid',
            name='typeName',
            field=models.CharField(
                db_index=True,
                help_text='(max. 100 characters)',
                max_length=100,
                verbose_name='Type name',
            ),
        ),
    ]
