# Generated by Django 2.1.5 on 2019-02-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0032_auto_20190227_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskagenda',
            options={'permissions': (('can_reset', 'Can reset task agendas'),)},
        ),
    ]
