# Generated by Django 2.1.5 on 2019-05-25 05:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            'EvalData',
            '0035_directassessmentcontextresult_directassessmentcontexttask',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpairwithcontext',
            name='sourceContextLeft',
            field=models.TextField(
                blank=True, null=True, verbose_name='Source context (left)'
            ),
        ),
        migrations.AlterField(
            model_name='textpairwithcontext',
            name='sourceContextRight',
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name='Source context (right)',
            ),
        ),
        migrations.AlterField(
            model_name='textpairwithcontext',
            name='targetContextLeft',
            field=models.TextField(
                blank=True, null=True, verbose_name='Target context (left)'
            ),
        ),
        migrations.AlterField(
            model_name='textpairwithcontext',
            name='targetContextRight',
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name='Target context (right)',
            ),
        ),
    ]
