# Generated by Django 2.2.12 on 2020-06-04 16:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0039_auto_20200601_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsegmentwithtwotargets',
            name='contextLeft',
            field=models.TextField(
                blank=True, null=True, verbose_name='Context (left)'
            ),
        ),
        migrations.AddField(
            model_name='textsegmentwithtwotargets',
            name='contextRight',
            field=models.TextField(
                blank=True, null=True, verbose_name='Context (right)'
            ),
        ),
    ]
