# Generated by Django 2.2.12 on 2020-10-12 12:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0042_dataassessmentresult_dataassessmenttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataassessmentresult',
            name='rank',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='(value in range=[1,100])',
                null=True,
                verbose_name='Score',
            ),
        ),
    ]
