# Generated by Django 2.2.12 on 2020-10-16 09:17
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0043_dataassessmentresult_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPairWithDomain',
            fields=[
                (
                    'textpair_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='EvalData.TextPair',
                    ),
                ),
                (
                    'documentDomain',
                    models.CharField(
                        help_text='(max. 1000 characters)',
                        max_length=1000,
                        verbose_name='Domain',
                    ),
                ),
                (
                    'documentURL',
                    models.TextField(blank=True, verbose_name='URL'),
                ),
            ],
            options={
                'ordering': ['_str_name'],
                'abstract': False,
            },
            bases=('EvalData.textpair',),
        ),
        migrations.AlterField(
            model_name='dataassessmentresult',
            name='item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='evaldata_dataassessmentresult_item',
                related_query_name='evaldata_dataassessmentresults',
                to='EvalData.TextPairWithDomain',
                verbose_name='Item',
            ),
        ),
        migrations.AlterField(
            model_name='dataassessmenttask',
            name='items',
            field=models.ManyToManyField(
                related_name='evaldata_dataassessmenttask_items',
                related_query_name='evaldata_dataassessmenttasks',
                to='EvalData.TextPairWithDomain',
                verbose_name='Items',
            ),
        ),
    ]
