# Generated by Django 2.2.12 on 2021-01-12 18:20
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0044_auto_20201016_0917'),
        ('EvalData', '0042_auto_20201006_1552'),
    ]

    operations = []  # type: ignore
