# Generated by Django 3.2.12 on 2022-06-29 13:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            'EvalData',
            '0048_pairwiseassessmentdocumentresult_pairwiseassessmentdocumenttask_textsegmentwithtwotargetswithcontext',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='textsegmentwithtwotargets',
            name='target1ContextLeft',
            field=models.TextField(
                blank=True, null=True, verbose_name='Target context (1)'
            ),
        ),
        migrations.AddField(
            model_name='textsegmentwithtwotargets',
            name='target2ContextLeft',
            field=models.TextField(
                blank=True, null=True, verbose_name='Target context (2)'
            ),
        ),
    ]
