# Generated by Django 3.2.12 on 2022-10-18 16:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0050_auto_20220801_0411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pairwiseassessmentresult',
            options={},
        ),
        migrations.AddField(
            model_name='pairwiseassessmentresult',
            name='errors1',
            field=models.TextField(
                blank=True,
                help_text='(max. 2000 characters)',
                max_length=2000,
                null=True,
                verbose_name='Errors (1)',
            ),
        ),
        migrations.AddField(
            model_name='pairwiseassessmentresult',
            name='errors2',
            field=models.TextField(
                blank=True,
                help_text='(max. 2000 characters)',
                max_length=2000,
                null=True,
                verbose_name='Errors (2)',
            ),
        ),
    ]
