# Generated by Django 4.2.22 on 2025-07-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EvalData", "0054_alter_dataassessmentresult_activatedby_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="domainName",
            field=models.CharField(
                help_text="(max. 50 characters)",
                max_length=50,
                verbose_name="Domain name",
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="marketID",
            field=models.CharField(editable=False, max_length=72, unique=True),
        ),
    ]
