# Generated by Django 4.1 on 2024-07-17 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Campaign', '0015_alter_campaign_activatedby_alter_campaign_batches_and_more'),
        ('EvalData', '0054_alter_dataassessmentresult_activatedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsegmentwithtwotargets',
            name='mqm1',
            field=models.TextField(blank=True, default='[]', verbose_name='MQM Annotations'),
        ),
        migrations.AddField(
            model_name='textsegmentwithtwotargets',
            name='mqm2',
            field=models.TextField(blank=True, default='[]', verbose_name='MQM Annotations'),
        ),
        migrations.CreateModel(
            name='PairwiseAssessmentDocumentESATask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('dateActivated', models.DateTimeField(blank=True, null=True, verbose_name='Date activated')),
                ('dateCompleted', models.DateTimeField(blank=True, null=True, verbose_name='Date completed')),
                ('dateRetired', models.DateTimeField(blank=True, null=True, verbose_name='Date retired')),
                ('dateModified', models.DateTimeField(blank=True, null=True, verbose_name='Date modified')),
                ('activated', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Activated?')),
                ('completed', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Completed?')),
                ('retired', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Retired?')),
                ('rawData', models.TextField(blank=True, editable=False, verbose_name='Raw data')),
                ('_str_name', models.TextField(blank=True, default='', editable=False)),
                ('requiredAnnotations', models.PositiveSmallIntegerField(help_text='(value in range=[1,50])', verbose_name='Required annotations')),
                ('batchNo', models.PositiveIntegerField(help_text='(1-based)', verbose_name='Batch number')),
                ('activatedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated_by', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Activated by')),
                ('assignedTo', models.ManyToManyField(blank=True, db_index=True, help_text='(users working on this task)', related_name='%(app_label)s_%(class)s_assignedTo', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('batchData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_batchData', related_query_name='%(app_label)s_%(class)ss', to='Campaign.campaigndata', verbose_name='Batch data')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_campaign', related_query_name='%(app_label)s_%(class)ss', to='Campaign.campaign', verbose_name='Campaign')),
                ('completedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_completed_by', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Completed by')),
                ('createdBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('items', models.ManyToManyField(related_name='%(app_label)s_%(class)s_items', related_query_name='%(app_label)s_%(class)ss', to='EvalData.textsegmentwithtwotargetswithcontext', verbose_name='Items')),
                ('modifiedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('retiredBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_retired_by', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Retired by')),
            ],
            options={
                'ordering': ['_str_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PairwiseAssessmentDocumentESAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('dateActivated', models.DateTimeField(blank=True, null=True, verbose_name='Date activated')),
                ('dateCompleted', models.DateTimeField(blank=True, null=True, verbose_name='Date completed')),
                ('dateRetired', models.DateTimeField(blank=True, null=True, verbose_name='Date retired')),
                ('dateModified', models.DateTimeField(blank=True, null=True, verbose_name='Date modified')),
                ('activated', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Activated?')),
                ('completed', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Completed?')),
                ('retired', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Retired?')),
                ('rawData', models.TextField(blank=True, editable=False, verbose_name='Raw data')),
                ('_str_name', models.TextField(blank=True, default='', editable=False)),
                ('score1', models.PositiveSmallIntegerField(help_text='(value in range=[1,100])', verbose_name='Score (1)')),
                ('score2', models.PositiveSmallIntegerField(blank=True, help_text='(value in range=[1,100])', null=True, verbose_name='Score (2)')),
                ('start_time', models.FloatField(help_text='(in seconds)', verbose_name='Start time')),
                ('end_time', models.FloatField(help_text='(in seconds)', verbose_name='End time')),
                ('activatedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated_by', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Activated by')),
                ('completedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_completed_by', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Completed by')),
                ('createdBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_item', related_query_name='%(app_label)s_%(class)ss', to='EvalData.textsegmentwithtwotargetswithcontext', verbose_name='Item')),
                ('modifiedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('retiredBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_retired_by', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Retired by')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_task', related_query_name='%(app_label)s_%(class)ss', to='EvalData.pairwiseassessmentdocumentesatask', verbose_name='Task')),
                ('mqm1', models.TextField(default='[]', help_text='MQM JSON string', verbose_name='MQM (1)')),
                ('mqm2', models.TextField(default='[]', help_text='MQM JSON string', verbose_name='MQM (2)')),
            ],
            options={
                'ordering': ['_str_name'],
                'abstract': False,
            },
        ),
    ]
