# Generated by Django 4.2.22 on 2025-11-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0057_pairwiseassessmentdocumentresult_browser_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairwiseassessmentdocumentresult',
            name='mqm1',
            field=models.TextField(default='[]', help_text='MQM JSON string', verbose_name='MQM (1)'),
        ),
        migrations.AddField(
            model_name='pairwiseassessmentdocumentresult',
            name='mqm2',
            field=models.TextField(default='[]', help_text='MQM JSON string', verbose_name='MQM (2)'),
        ),
    ]
