# Generated by Django 4.2.22 on 2025-12-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0058_pairwiseassessmentdocumentresult_mqm1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsegmentwithtwotargetswithcontext',
            name='documentID',
            field=models.CharField(help_text='(max. 200 characters)', max_length=200, verbose_name='Document ID'),
        ),
    ]
