# Generated by Django 4.2.22 on 2026-04-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0059_alter_textsegmentwithtwotargetswithcontext_documentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairwiseassessmentdocumentresult',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Annotator comment', verbose_name='Comment'),
        ),
    ]
